---
  - name: Elkserver
    hosts: elkservers
    remote_user: kali
    become: true
    tasks:

    - name: docker.io (state=present is optional)
      apt:
        force_apt_get: yes
        name: docker.io
        state: present

    - name: Install pip
      apt:
        force_apt_get: yes
        name: python-pip
        state: present

    - name: Install Docker python module
      pip:
        name: docker
        state: present

    - name: Optimize Memory
      command: sysctl -w vm.max_map_count=262144

    - name: Download and launch a docker web container
      docker_container:
        name: elk
        image: sebp/elk
        state: started
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044